# Generated by Django 5.1.7 on 2025-04-10 02:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order_confirmation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderconfirmation",
            name="sent_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
