# Generated by Django 5.2 on 2025-04-09 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="product_id",
        ),
        migrations.DeleteModel(
            name="Wishlist",
        ),
    ]
