# Generated by Django 5.1.7 on 2025-04-10 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0002_order_email_alter_order_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="discount",
            name="max_amount",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
