# Generated by Django 5.1.7 on 2025-04-10 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0003_discount_max_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="discount_coupon_used",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="checkout.discount",
            ),
        ),
    ]
