# Generated by Django 5.1.7 on 2025-04-16 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0004_order_discount_coupon_used"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={},
        ),
    ]
